### ISSUE TITLE
Repo tương tự

### ISSUE THREAD

**Issue by xluffy** [grokking-engineering/made_by_vietnamese#2]
Mình thấy có một repo tương tự, cũng có một số rồi nhưng hiện tại lại ko đc update lắm. Có thể dùng để tham khảo ^^

https://github.com/lewtds/awesome-viet-foss

**Comment by tieubao** [comment]
@xluffy :+1:

**Comment by nvquanghuy** [comment]
Thanks bạn @xluffy :+1: , tụi mình đã reach out đến bạn author của repo này để xin gộp nội dung vào và vẫn đang chờ reply :)
